-- markdown --

local md = {
  header = function(text, level)
    return ("#"):rep(level) .. " " .. text
  end,
  bold = function(text)
    return "**" .. text .. "**"
  end,
  italic = function(text)
    return "_" .. text .. "_"
  end,
  color = function(text)
    return text
  end,
  code = function(text, lang)
    return "\n```" .. lang .. "\n" .. text .. "\n" .. "```" .. "\n"
  end,
  monospace = function(text)
    return "`" .. text .. "`"
  end,
  resized = function(text, size)
    return text
  end,
}

function md.postprocess(text)
  text = text:gsub(" +", " "):gsub("\n", "\n\n")
  text = text ..
    "\n\n\n\n##### _this documentation was autogenerated by .docgen._"
  return text
end

return md
